### ISSUE TITLE
Can't compile with openssl 0.9

### ISSUE THREAD

**Issue by e-oz** [sfackler/rust-openssl-verify#3]
```bash
error[E0432]: unresolved import `openssl::x509::GeneralNames`
  --> /Users/OZ/.cargo/git/checkouts/rust-openssl-verify-5cd34518ea1d29af/master/src/lib.rs:42:51
   |
42 | use openssl::x509::{X509StoreContextRef, X509Ref, GeneralNames, X509NameRef};
   |                                                   ^^^^^^^^^^^^ no `GeneralNames` in `openssl::x509`. Did you mean to use `GeneralName`?

error: the type of this value must be known in this context
  --> /Users/OZ/.cargo/git/checkouts/rust-openssl-verify-5cd34518ea1d29af/master/src/lib.rs:78:39
   |
78 |                 if let Some(actual) = name.ipaddress() {
   |                                       ^^^^^^^^^^^^^^^^

error: no method named `text_by_nid` found for type `&openssl::x509::X509NameRef` in the current scope
  --> /Users/OZ/.cargo/git/checkouts/rust-openssl-verify-5cd34518ea1d29af/master/src/lib.rs:98:41
   |
98 |     if let Some(pattern) = subject_name.text_by_nid(nid::COMMONNAME) {
   |                                         ^^^^^^^^^^^

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
  --> /Users/OZ/.cargo/git/checkouts/rust-openssl-verify-5cd34518ea1d29af/master/src/lib.rs:98:17
   |
98 |     if let Some(pattern) = subject_name.text_by_nid(nid::COMMONNAME) {
   |                 ^^^^^^^ trait `str: std::marker::Sized` not satisfied
   |
   = note: `str` does not have a constant size known at compile-time
   = note: all local variables must have a statically known size

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
  --> /Users/OZ/.cargo/git/checkouts/rust-openssl-verify-5cd34518ea1d29af/master/src/lib.rs:98:12
   |
98 |     if let Some(pattern) = subject_name.text_by_nid(nid::COMMONNAME) {
   |            ^^^^^^^^^^^^^ trait `str: std::marker::Sized` not satisfied
   |
   = note: `str` does not have a constant size known at compile-time
   = note: required by `std::prelude::v1::Some`

error: aborting due to 4 previous errors

Build failed, waiting for other jobs to finish...
```

**Comment by sfackler** [comment]
`SslConnector` should be used instead of this crate on 0.9. I'll update the README here to note that.

**Comment by e-oz** [comment]
I'm afraid it will not change list of dependencies of Hyper. But thanks.

**Comment by sfackler** [comment]
I've updated the master branch to build against 0.9. I don't think I'll publish it but it should help when `[replace]`ing stuff.

**Comment by e-oz** [comment]
thank you very much for your time!
